machine:
  services:
    - docker
  environment:
    VERSION: 1.0
    IMAGE: blurrcat/alpine-python-psycopg2:$VERSION

dependencies:
  override:
    - docker info
    - docker build -t $IMAGE .

test:
  override:
    - docker run -v `pwd`/test.py:/test.py --env DATABASE_URL=postgresql://localhost/circle_test --net host $IMAGE python /test.py

deployment:
  hub:
    branch: master
    commands:
      - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
      - docker push $IMAGE
